name = "imyong-study"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next"

[[d1_databases]]
binding = "DB"
database_name = "exam-db"
database_id = "3f76550b-a328-41ee-a2e2-0d7389050a15"

[vars]
OPENAI_API_KEY = ""
